uploads = []

[[generated]]
id = "iaHuPm0txqdooXj0e-Aac"
uri = "file://artifacts/audio-downloader/public/logo.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "I4pvpSDXE0l4y9JFQ-SYk"
uri = "file://artifacts/audio-downloader/public/logo.png"
type = "image"
title = "RIPPD Logo (Crystal Gem)"
